baseurl = "https://nuvent.io/"
languageCode = "en-US"
theme = "casper"
title = "Nuvent"
[pagination]
  pagerSize = 4
pluralizelisttitles = false
Copyright = "All rights reserved - &copy;2025"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  description = "Dynamic Infrastructure Orchestration."
  cover = "img/cover-page.jpg"
  author = "@nuvent"
  logo = "img/logo.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "nuvent"
  twitterName = "nuvent"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[menu]
  [[menu.main]]
    name = "Blog"
    weight = 3
    identifier = "blog"
    url = "/"

  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about"

  [[menu.main]]
    name = "Contact"
    weight = 2
    identifier = "contact"
    url = "/contact"
